### ISSUE TITLE
Python version requirement?

### ISSUE THREAD

**Issue by rhine3** [jhuus/HawkEars1#1]
Hi Jan! I'm Tessa Rhinehart, a PhD student at the University of Pittsburgh. Elly mentored me on a project last summer at the University of Alberta. I'm going to give HawkEars a try for analyzing our data!

I mostly wanted to introduce myself here, but also to add a note: for me, when I first created a conda environment for HawkEars on my computer, conda automatically created a Python 3.12 environment. But when installing the requirements.txt, pip threw an error, which turns out to be related to Python v3.12: https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean. This isn't really a HawkEars-specific issue, but perhaps you could suggest in the README that users use Python v3.11 or below.

**Comment by jhuus** [comment]
Hi Tessa. Thanks for letting me know! I’ll add a note saying to use Python
3.11 for now. If your recordings are from Pittsburgh you may have some
species that HawkEars doesn’t support, e.g. Prairie Warbler comes to mind.
Anyway, let me know how it goes.

Jan

**Comment by rhine3** [comment]
Thanks for the note!! That's good to know. For my first test, I'm just analyzing some data collected with Elly and Erin in Alberta last summer. But other projects of mine/my lab focus on more southerly species--including Prairie Warblers!

**Comment by jhuus** [comment]
When you get to the more southern data, make a list of the extra species
you need, and I can consider adding those for you.

Jan

**Comment by jhuus** [comment]
HawkEars now supports Python 3.12.
