### ISSUE TITLE
Add tags for release versions

### ISSUE THREAD

**Issue by sammlapp** [jhuus/HawkEars1#2]
For reproducibility of analysis results, it would be very helpful to tag versions of the code base. Then, you could pip install or git checkout a specific tag to make sure you can get consistent results / re-use code without it breaking, e.g. on tag v0.1.0, v0.2.0 etc.

**Comment by jhuus** [comment]
Good idea! I just created two releases: 0.0.9 (previous) and 0.1.0 (current). Let me know if you have any further suggestions to improve that, but otherwise I'll do a release whenever there's a change that affects the inference results.

**Comment by jhuus** [comment]
Closed.
